### ISSUE TITLE
Torf crashes when using Batch Mode (Windows 11)

### ISSUE THREAD

**Issue by Lebon14** [SavageCore/torf-gui#11]
Hey there. Using the latest version 0.2.4

I wanted to create some torrent files. So, I have all the folders I want to upload into a single folder and select that folder.
Then, I check "Batch mode", enter my announce URL for (insert private torrent tracker here) and check "private torrent". To finish, I click create and select a destination folder.

The app just crashes. No errors. No nothing.
Selecting a single folder works, however.

At first, I thought it was because my folders were on my NAS on a network drive. So, I moved that to my C:\ drive. Same issue.
Then, I thought it was because I was running torf from a folder on my NAS and could somehow crash because it couldn't write the .ini file. Nope.

Windows 11 Pro x64
AMD Ryzen 9 5900X (stock)
64GB DDR4 CL16 (using XMP profile)
EVGA GeForce RTX 3070 Ti

I'm here to help diagnose.
I will finish doing the folders one by one and, if for some reason, it crashes on a certain one, I will update this post to try to see what's up.

Cheers.

**Comment by SavageCore** [comment]
Thanks, that's a known issue [#3]
