### ISSUE TITLE
Support sub-folders in Batch Mode

### ISSUE THREAD

**Issue by SavageCore** [SavageCore/torf-gui#12]
Currently in batch mode, if you select the folder structure below you get the following message: "Input path must be non-empty"

```
folder
	sub-folder
		file
	sub-folder
		file
```

We should extend batch creation to handle this case.

**Comment by Lebon14** [comment]
Any news on the progress of this? Just asking. No rush.

**Comment by SavageCore** [comment]
> Any news on the progress of this? Just asking. No rush.

I shall try to get to this next week, perhaps over this weekend!
