### ISSUE TITLE
Batch mode creates a torrent of each individual files in each folder (with or without subfolders)

### ISSUE THREAD

**Issue by Lebon14** [SavageCore/torf-gui#20]
Batch mode is still not fixed it seems; in fact, it's even more broken.

So, I select a folder where I have two folders I want a torrent for. So, I select "Batch mode".

But, then, instead of creating a single torrent for each folder, it creates a torrent file for each files in each folders recursively.

So,

```
Top Folder Name 1
     Sub Folder 1
          File 1.flac
          File 2.flac
          File 3.flac
          cover art.jpg
     Sub Folder 2
          File 4.flac
          File 5.flac
          File 6.flac
          cover art.jpg

Top Folder Name 2
     Sub Folder 3
          File 7.flac
          File 8.flac
          File 9.flac
          cover art.jpg
     Sub Folder 4
          File A.flac
          File B.flac
          File C.flac
          cover art.jpg
```

So, torf, in this case, will create "File 1.flac.torrent", "File 2.flac.torrent" (...) "File 6.flac.torrent" and "cover art.jpg.torrent" instead of "Top Folder Name 1.torrent" and "Top Folder Name 2.torrent". And that for all the files in the folder you selected to create torrents in batch for.

This still happens if files aren't in sub-folders. Like:

```
Top Folder Name 3
     File D.flac
     File E.flac
     File F.flac
     cover.jpg

Top Folder Name 4
     File G.flac
     File H.flac
     File I.flac
     cover.jpg
```
In that case, it'll create "File D.flac.torrent", "File E.flac.torrent" (...) "File I.flac.torrent" and "cover.jpg.torrent" instead of "Top Folder Name 3.torrent" and "Top Folder Name 4.torrent".

torf works correctly if you do them one by one.

Those were my settings when trying to batch (removed tracker URLs since it's not public):
![image](https://github.com/SavageCore/torf-gui/assets/5299469/7dde4d2c-5ee7-4a7a-92fa-124a229ffaff)

**Comment by SavageCore** [comment]
You're right, I messed up that logic! I'll get a fix out ASAP.

**Comment by SavageCore** [comment]
@Lebon14 

Please try this version:
https://github.com/SavageCore/torf-gui/actions/runs/7838906302/artifacts/1232174973

Is this behaving as expected?

**Comment by Lebon14** [comment]
Seems to work fine now.
Thanks for the quick fix.

**Comment by SavageCore** [comment]
Thanks for confirming, will push a release now!
