### ISSUE TITLE
batch mode crash

### ISSUE THREAD

**Issue by evafans** [SavageCore/torf-gui#3]
batch mode never work on my end, it crashes on both of my computers (win 10 and 11).
single mode works fine.

**Comment by SavageCore** [comment]
I have a fix for this incoming, it's currently in the https://github.com/SavageCore/torf-gui/tree/feature/mediainfo branch. I'll try and rip that out and make a quick release later today, thanks.

**Comment by SavageCore** [comment]
Released as v0.2.1

**Comment by evafans** [comment]
If it's files inside a forder, it works.
Forders inside a forder, still crashes.

**Comment by Brenex** [comment]
Sorry, I just realize this is what I experienced today too

**Comment by SavageCore** [comment]
Worth noting dottorrent-gui displays `Input path must be non-empty` when selecting a folder of folders like so:

```
folder/
		subfolder/
						file
		subfolder2/
						file
		subfolder3/
						file

**Comment by Lebon14** [comment]
As far as I know, most folders had sub-folders and none were empty.

**Comment by SavageCore** [comment]
I decided to fix this in the same way as dottorrent-gui, thus preventing the hard crash. I've created #12 to track this.

**Comment by Brenex** [comment]
Doesn't work for me: 
![CleanShot 2023-11-04 at 22 59 04@2x](https://github.com/SavageCore/torf-gui/assets/3178983/f1e905e7-89a5-4c20-8ec5-5be88d77a078)

**Comment by SavageCore** [comment]
@Brenex That's the expected behaviour now. Emulating `dottorrent-gui`. #12 will allow it to work once done.
