### ISSUE TITLE
Allow setting 32MB piece size

### ISSUE THREAD

**Issue by Pentaphon** [SavageCore/torf-gui#8]
All modern clients support this so please support creating 32MB piece size torrents.

**Comment by SavageCore** [comment]
That is something you will have to request at the [torf](https://github.com/rndusr/torf) repo

**Comment by Pentaphon** [comment]
Looks like a bugfix was necessary to make this work. See https://github.com/rndusr/torf/issues/33

**Comment by SavageCore** [comment]
Oh cool, I will publish a new release tomorrow!

**Comment by SavageCore** [comment]
Released as 0.2.6!
